Modules/Inventory/Http/routes.php
<?php

Route::group(['middleware' => ['web','auth'], 'prefix' => 'inventory', 'namespace' => 'Modules\Inventory\Http\Controllers'], function()
{
    Route::get('/', 'InventoryController@index')->name("inventory.index");
    // Route::resource('EveryFiles','EveryFilesController');
    // Route::resource('Forward','InventoryController');
    // Route::resource('Archive','FileArchiveController');
    
    // ===== DISPLAY ACCOUNT =====
    Route::get('/mine/ACCOUNT_KO_TO','HomeController@homePage')->name('DisplayAccount');
    
    

// ======================================================================================================
// ===== BOTH RECEIVER AND SENDER ACTIONS ======
// ======================================================================================================
    // = 1. HOME PAGE =
    Route::get('/mine/HOME','HomeController@homePage')->name('DisplayHomePage');
    // = 2. CREATE FILE =
    Route::resource('Conversations','ConvFilesController');
    // = 3. DISPLAYS ALL FILES
    Route::get('/mine/INBOX','EveryFilesController@receivedFiles')->name('display.RECEIVED'); // RECEIVED FILES
    Route::get('/mine/OUTBOX','EveryFilesController@sentFiles')->name('display.SENT'); // SENT FILES
    Route::get('/mine/MESSAGES','EveryFilesController@allFiles')->name('display.ALL'); // ALL FILES
    Route::get('/mine/IMPORTANT','EveryFilesController@importantFiles')->name('display.IMPS'); // IMPORTANT FILES
    Route::get('/mine/ARCHIVED','EveryFilesController@ArchivedFiles')->name('display.ARCHIVE'); // ARCHIVED FILES
    Route::get('/mine/REPORTS','EveryFilesController@REPORTS')->name('display.REPORTS'); // REPORT FILES
    Route::get('/mine/DASHY','EveryFilesController@DASHY')->name('displaySdashboard'); // DASHBOARD
    
    // report view of admin -- new
    Route::get('/ReportGeneration','ReportPrintController@viewReport')->name('admin.REPORTS'); // REPORT FILES
    Route::get('/ReportGeneration/view', array('uses' => 'ReportPrintController@GenerateReports'))->name('admin.gREPORTS');
    Route::get('/ReportGeneration/view/print', array('uses' => 'ReportPrintController@PrintReports'))->name('admin.pREPORTS');
    Route::get('/ReportGeneration/view/browser', array('uses' => 'ReportPrintController@ViewReportinBrowser'))->name('admin.vREPORTS');
    


// ======================================================================================================
// ===== SENDER ACTIONS ======
// ======================================================================================================
    // = 01. VIEW SPECIFIC FILE =
    Route::get('SentFile/{tno}', ['as' => 'SpecificFileSender', 'uses' => 'SpecificFileSenderController@SpecificFileSender']);
    // = 02. MARK FILE IMPORTANT/NOT =
    Route::get('IMPORTANT/{TNO}', ['as' => 'MarkImp', 'uses' => 'FlagController@MarkFileImportant']);

    

    // = 04. RESTORE FILE =
    Route::get('SenderRestore/{tno}/{sender}', ['as' => 'senderRestore', 'uses' => 'FileArchiveController@SenderRestore']);
    // = 05. CHANGE ROUTE OF RECEIVERS =
    Route::post('FileRoute/{tno}/{sender}', ['as' => 'SendChangeRoute', 'uses' => 'SpecificFileSenderController@SendChangesRoute']);
    // = 06. REMOVE NOTIFICATION SENT BY ROUTE PROBLEM
    Route::get('FileRouteNotif/{tno}', ['as' => 'CheckNotif', 'uses' => 'SpecificFileSenderController@CheckNotifs']);
    // = 4. GENERATE REPORTS =
    //Route::get('/mine/Generate','SpecificFileSenderController@DASHY')->name('GenerateReport'); // GenerateReport
    Route::post('REPORTS/Generate', ['as' => 'GenerateReport', 'uses' => 'ReportPrintController@GenerateReports']);
    

// ======================================================================================================
// ===== RECEIVER ACTIONS ======
// ======================================================================================================
    // = 6. VIEW SPECIFIC FILES =
      // = 6A. NORMAL FILE =
      Route::get('ViewFile/{track}/user/{rec}/{sender}', ['as' => 'SpecificFileReceiver', 'uses' => 'SpecificFileController@SpecificFileReceiver']);
      // = 6B. ROUTE FILE =
      Route::get('FileRoute/{track}/user/{rec}/{acpt}/{ANum}', ['as' => 'SpecificFileReceiverInARoute', 'uses' => 'SpecificFileController@SpecificFileReceiverInARoute']);  

    // ====== FORWARD ROUTE DOCUMENTS FILE ====== //
    	Route::get('ForwardDocuments/{track}/{deptName}/{deptID}/{NUM}', ['as' => 'forwardDocs', 'uses' => 'ForwardDocumentController@ForwardDocument']);    

    // ====== FORWARD FILE ====== //
    	Route::post('ForwardByRec/{track}/user/{forwRec}', ['as' => 'forwardByRec', 'uses' => 'ForwardController@ForwardByReceiver']);

    // ====== REPLY ============= //
    	Route::post('Reply/{track}/user', ['as' => 'ReplyShit', 'uses' => 'ReplyController@RepyShit']);

    // ====== ACCEPT FILE ======= //
	Route::get('Accept/NO/{track}/DOC/{docNAME}/DEPARTMENT/{dept}', ['as' => 'AcceptFiles', 'uses' => 'AcceptFileController@AcceptFile']);

    // ====== DOWNLOAD FILE ===== //
    	Route::get('Download/{tno}/{attachName}/{sender}', ['as' => 'DownloadFile', 'uses' => 'DLController@DownloadFile']);

    // = 9. CHANGE ROUTE OF THE FILE AND NOTIFIES THE SENDER
    Route::post('FileRoute/{tno}/user/{rec}/ChangeRouteReceiver', ['as' => 'changeROUTErec', 'uses' => 'SpecificFileController@ChangeRouteRec']);
    Route::post('FileRoute/{tno}/user/{rec}/ChangeRouteReceiverNotify',['as'=>'changeROUTErecNotif','uses'=>'SpecificFileController@ChangeRouteRecNotif']);

    // ====== ARCHIVE FILE ============= //
    Route::get('ArchivesFile/{tno}/{titles}', ['as' => 'ArchiveFiles', 'uses' => 'FileArchiveController@ArchiveFile']);
    // ====== RESTORE FILE ============= //
    Route::get('Restore/{transNO}/{titles}', ['as' => 'RestoreFiles', 'uses' => 'FileArchiveController@RestoreFile']);

// ======================================================================================================
// ======================================================================================================
// ======================================================================================================    

    // ===== VIEW SPECIFIC FILE SENDER =====
    

});

Modules/Inventory/Resources/views/FileManagement/MODALS.blade.php
<!-- ===== MODAL FOR IMPORTANT CHANGE ALERT ==== -->
<div class="modal fade" id="ImpAlert" type="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <center><h3>IMPORTANT FILE ALERT!</h3></center>
        <center style="font-weight: bolder;">You can only change the importance of the file if you are the sender.</center>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<!-- ===== MODAL FOR CANNOT DOWNLOAD FILE ALERT ==== -->
<div class="modal fade" id="NoDownloadFileAlert" type="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <center><h3>ATTACHMENT ALERT!</h3></center>
        <center style="font-weight: bolder;">The sender did not upload any file.</center>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- ===== MODAL FOR FILE ALREADY ACCEPTED ALERT ==== -->
<div class="modal fade" id="AlreadyAcptNotif" type="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <center><h3>- FILE ACCEPTED -</h3></center>
        <center style="font-weight: bolder;">You already accepted the file. THANKS </center>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- ===== MODAL FOR NO FILES RECEIVED ==== -->
<div class="modal fade" id="NoFileToAccept" type="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <center><h3>- YOU HAVE NO FILE TO ACCEPT -</h3></center>
        <center style="font-weight: bolder;">There are no documents or files sent your way. This is an infomative message from the sender. </center>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- ===== MODAL FOR THAT CANNOT BE ACCEPTED DUE TO ROUTES ==== -->
<div class="modal fade" id="AcptNotifNOTyet" type="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <center><h3>- DELETE FILE ALERT! -</h3></center>
        <center style="font-weight: bolder;">You cannot accept the file yet because the previous receiver has not yet accepted the file. <br>Please Check the <b>ROUTE INFORMATION</b> to know the receiver before you.</center>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- ===== MODAL FOR CANNOT DELETE FILE ALERT ==== -->
<div class="modal fade" id="CANNOTdeleteAlert" type="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <center><h3>- DELETE FILE ALERT! -</h3></center>
        <center style="font-weight: bolder;">You cannot delete the file if you have not accepted the file yet. THANK YOU! </center>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

Modules/Inventory/Resources/views/FileManagement/_otherFile.blade.php
<script type="text/javascript">
      $(document).ready(function(){
        setInterval(function(){
              $("#importantsTBL").load(location.href+" #importantsTBL>*","");
              $("#NOTIFICATIONSSTUFF").load(location.href+" #NOTIFICATIONSSTUFF>*","");
              $("#NOTIFICATIONSSTUFFALERT").show('slow');
              $("#FOoTERCTRS").load(location.href+" #FOoTERCTRS>*","");
        }, 3000);
      });
</script>
<table id="importantsTBL" class="table table-striped table-bordered table-hover">
    <thead id="tableHeader">
        <td style="max-width:50px;"></td>
        <td style="max-width:100px; min-width: 100px;">TRACKING NUMBER</td>
        <td>SUBJECT</td>
        <td colspan="3">FILE STATUS</td>
        
    </thead>
    <?php
	foreach($_file as $s){
		if($tite_page == 'Archived Files'){
			if($s->INVOLVED == 'TRUE'){
			  echo "<tbody><td>";
				if($s->sendID == $USERID){ ?>
				  <a href="{{route('senderRestore', ['tno'=>$s->transNO,'sender'=>$tite_page]) }}" class="btn stuff" style="padding: 0px; margin:0px;"><?php
				}else{ ?>
		                  <a href="{{route('RecRestore',['tno'=>$s->transNO,'rec'=>$userHere,])}}" class="btn stuff" style="padding: 0px; margin:0px;"><?php
				}
				echo "<button class='btn btn-primary'>Restore</button>";
				echo "<span class='hoverstext'>Restore This Archived File</span>";
                    		echo "</a> &nbsp;";
			  echo "</td><td>";
				echo "<b>$s->transNO | $s->docTYPE </b><br>";
				if($s->IMP == 1){echo "<i><b>IMPORTANT FILE</b></i>";}
				else{echo "<i>FILE NOT IMPORTANT</i>";}
				echo "<br><i class='fa fa-paperclip'></i>$s->attachNAME";
			  echo "</td><td>";
				echo "Subject: $s->SUBJ <br> Message: $s->MSG";
			  echo "</td><td>";
				if($s->sendID == $USERID){echo "Archived: $s->dateARCHIVED";}
				else{
					
				}
			  echo "</td></tbody>";
			}else{}
		}elseif($tite_page == 'All Files'){	
			if($s->INVOLVED == 'TRUE'){
			   if($s->IMP == 1){echo "<tbody style='color:red;'>";}
			   else{echo "<tbody>";}
				echo"<td>";	?>
				   <a href="{{route('SpecificFileReceiver',['track'=>$s->transNO,'rec'=>$userHere,'sender'=>$s->SenderDept.' | '.$s->SenderName]) }}" 
					class="btn stuff" style="padding: 0px; margin:0px;"><i class="fa fa-eye"></i>
					<span class="hoverstext">View File</span> </a> &nbsp;

				   <a href="{{route('RouteArchive',['track'=>$s->transNO,'rec'=>$userHere,'titlePage'=>$tite_page]) }}" class="btn stuff" style="padding: 0px; margin:0px;">
					<i class="fa fa-trash"></i><span class="hoverstext">Delete Message</span>
                        		</a> &nbsp;<?php
				echo "</td><td>";
				   echo "<span style='font-size:20px;'><b>$s->transNO</b></span> <br> 
				   <span style='font-size:medium;'><b>".strtoupper($s->docTYPE)."</b></span> <br> 
				   <b>Date Received: </b>$s->SenderDateSENT";
				echo "</td><td>";
				   echo "<b>Sender: </b> $s->SenderDept | $s->SenderName <br>";
				   echo "<b>Subject: </b>$s->SUBJ <br>";
				   if($s->ROUTESTAT == 1){echo "<b>FILE IN A ROUTE</b><br>";}
					echo "<b><i class='fa fa-paperclip'></i>Attachment: </b>$s->attachNAME";
			
				echo "</td><td> <div id='statuses'>";
				   if($s->recTYPE == "PERSONAL MESSAGE"){echo "NO STATUS FOR PERSONAL MESSAGE";}
				   else{
			   		foreach(unserialize($s->fileSTATS) as $a){
			   			foreach($a as $b){
				   		   if($b['EmpDEPT'] == $userDATA->dept_name){
						    foreach (array_keys($b['Documents']) as $c){
							echo "<b>".strtoupper($c).":</b> ";
							if($b['Documents'][$c] == "N"){echo "&nbsp;  &nbsp; <span style='color:red;'>Not Accepted</span><br>";}
							else{echo "&nbsp;  &nbsp; ".$b['Documents'][$c]."<br>";}
						    }
					
				   		}
			   		}
			   	   }
				}
				echo "</div></td></tbody>";
	  		}

		}
	}
    ?>
    
</table>
<div id="FOoTERCTRS">
    <center>{{ $_file->links() }}</center>
        <?php if ($counterOthersPage== 0){ echo "<h3><center>-- EMPTY FOLDER --</center></h3>"; } ?>	
</div>

Modules/Inventory/Resources/views/FileManagement/createFile.blade.php
<!-- CALLS SCRIPT -->
@include('inventory::scripts._selectRouteReceivers')
@include('inventory::scripts._selectMultipleRecs')

<!-- ___________________MODAL TO CREATE NEW FILE__________________ -->
  <div class="modal fade" id="modal-create-file" type="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header headerStyle">
          <h3><span id="MessageTitle">Create Document</span> 
            <button type="button" class="fa fa-times" data-dismiss="modal" id="btnt"></button>
          </h3>
        </div>
        <div class="modal-body"> 
          <i style="font-size:12px; color:red;">Note: Fields with asterisks are required.</i>
          <i style="font-size:12px; color:red;" class="NoteNOTIF" id="hideThis"></i>
          <i style="font-size:12px; color:red;" class="errorNOTIF" id="hideThis"></i>
	<div id="selRecsWrapper">
          <span id="suckME">SELECTED RECEIVERS:</span>
          
          <textarea type="text" id="ALLselectedRECS" placeholder="SELECTED RECEIVERS" name="ALLselectedRECS" class="form-control textContent" value="NAMES" disabled required style="display:none;">
          </textarea>
          <div style="border:3px solid #c0c0c0; width:100%; z-index:9; background:#fff; border-radius:4px; overflow:auto; max-height:100px;min-height:100px;">
          <div id ="nameWrapper" style="max-height:100px;min-height:100px;font-size:15px;"></div>
          </div>
          <button type="button" class="btn btn-primary pull-right" id="CLEARSELCTEDNAMES">CLEAR SELECTED</button><br>
         </div>
<!-- ==================================== CREATE FILE ==================================== -->
  <div style="padding:0px;">
    <form class="form-horizontal" file='true' type="form" enctype="multipart/form-data" method="post" action="{{ URL::route('Conversations.store') }}" >
    {{ csrf_field() }}
      <div class="form-group">
        <!-- == SELECT RECEIVER == -->
        <div class="modal-body" data-spy="scroll" data-target="#scrollers" data-offset="50">
          <!-- == SELECT RECEIVER TYPE == -->
          <span>SELECT RECEIVER TYPE<i id="reqStyle">*</i></span>
          <select class="form-control textContent" id="smOsr" required name="smOsr">
            <option value="none">SELECT RECEIVER TYPE</option>
            <option value="sm">Multiple Departments</option>
            <option value="sr">Route Departments</option>
            <option value="sa">All Departments</option>
            <option value="pm">Personal Message</option>
          </select>

          <div id="scrollers">  
            <!-- === MULTIPLE RECEIVERS === -->
            <span id='MR' >
              <span>SELECT RECEIVER</span>
              <select id="SelectReceiverForMultiple" class="form-control textContent" name="PMNames">
                <option value="none" name="none">SELECT RECEIVER</option>
  
                @foreach($deptRecs as $emps13)
                  <option value="{{array_search ($emps13, $deptRecs)}}" name="{{$emps13}}" 
                    id="OptionReceiverForMultiple"> {{$emps13}}
                  </option>
                @endforeach
              </select>
            </span>
            
            <!-- === PERSONNAL MESSAGES == -->
            <span id='PM'>
            <span>SELECT RECEIVER</span>
              <select id="SelectReceiverForPM" class="form-control textContent">
                <option value="none" name="none">SELECT RECEIVER</option>
                @foreach($emps as $emps13)
                  <option value="{{$emps13->emp_id}}" name="{{$emps13->dept_name}} - {{$emps13->f_name}} {{$emps13->l_name}}"
                    id="OptionReceiverForPM"> {{$emps13->dept_name}} - {{$emps13->f_name}} {{$emps13->l_name}}
                  </option>
                @endforeach
              </select>
            </span>

          </div>
                  
    <!-- == FILE TYPE == -->
    <span>Document Type <i id="reqStyle">*</i></span>
    <div>
      <select class="form-control textContent" id="thisSelect" name="docTYPE" required>
        <option value="">SELECT DOCUMENT TYPE</option>
        @foreach($ftypes as $ftypes)
          <option value="{{$ftypes->filetype_id}}">{{$ftypes->filetype_name}}</option>
        @endforeach
      </select>
    </div>
    <!-- == SUBJECT == -->
    <span>Subject <i id="reqStyle">*</i></span>
    <input type="text" class="form-control textContent" placeholder="Subject" id="a2-style" name="a2-data" required>

    <!-- == MESSAGE == -->
    <span>Message</span>
    <textarea type="text" class="form-control textContent" placeholder="Message..." name="MSGhere" id="MessageInput"></textarea>

    <!-- == URGENT == -->
    <div class="col-sm-12">
    <span class="control-label float-left" for="Urgent">Urgent </span>
      <section title=".slideThree">
        <div class="slideThree">  
          <input type="checkbox" value="1" id="slideThree" name="a0-data" />
          <label for="slideThree"></label>
        </div>
      </section>
     </div>

    <!-- == HARD COPY == -->
    	<div class="col-sm-12" id="pmHC">
	<span class="control-label float-left" for="HardCopy">Hard Copy </span>
	      <section>
	        <div class="col-sm-3" id="ccheckHere"> <input type="checkbox" value="0" name="HardCopy" id="HardCopy"/></div>
	        <div class="col-sm-9" style="border-left:2px solid #c0c0c0; display:none;" id="hcNames">
	        	
	        	<div class="inputWrapper">
	        	<input type="text" class="form-control textContent" placeholder="Document Name" id="docName" name="docName[]" style="max-width:50%;">
	        	
	        	</div>
	        	<br><button class="btn btn-new btn-sm" id="addDocName">Add Document</button>
	        	
	        	
	        </div>
	      </section>
	      <br>
	</div>

     

  </div> <!-- END MODAL BODY -->
</div> <!-- END FORM GROUP -->

<!-- === FILE ATTACHMENT SOFT COPY === --> 
<div class="form-group" id="attachSoftFile">
  <i style="font-size:12px; color:#c0c0c0;" class="btn stuff">
    NOTE: File Extension that can be uploaded (.ppt, .txt, .docx, .xls, .png, .jpeg, .jpg, .doc, .pdf)
    <span class="hoverstext">List of all file extensions that can be uploaded<br> .ppt, .txt, .docx, .xls, .png, .jpeg, .jpg, .php, .gif, <br> .doc, .pdf</span>
  </i>
  <input type="file" class="form-control textContent" name="a5-data" id="filea5" style="border:none;">
</div>


<!-- === HIDDEN DATA === -->
<div id="hideThis">
    <input type="text" name="a1-data"  id="receiver" >
    <input typ='text' name='routeShit' id='routeShit'>
</div>

  <div class="modal-footer">
    <input type="submit" value="Send File" name="submit" class="btn btn-new" >
    <button type="button" class="btn btn-danger" data-dismiss="modal" id="CancelCompose">Cancel</button>
  </div>

</form>

</div>
            
<!-- ==================================== CREATE URGENT FILE ==================================== -->
            
      </div>
    </div>
  </div>
</div>


@section('plugins-script')
    <script src="{{asset('adminlte')}}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/daterangepicker/moment.js"></script>
    <!-- <script src="{{asset('js')}}/jquery.min.js"></script> -->
    <script src="{{asset('js')}}/moment.min.js"></script>
    <script src="{{asset('js')}}/fullcalendar.min.js"></script>
@stop